const $ = (s) => document.querySelector(s);
const api = (name, opts={}) => fetch(`/.netlify/functions/${name}`, { credentials:'include', headers:{'Content-Type':'application/json', ...(opts.headers||{})}, ...opts }).then(async r => { const j = await r.json().catch(()=>({})); if(!r.ok) throw new Error(j.error||'Request failed'); return j; });
const statuses = ['Pending','Under Review','Approved','Rejected'];

if ($('#loginForm')) {
  $('#loginForm').addEventListener('submit', async e => { e.preventDefault(); const f = new FormData(e.target); $('#loginNotice').textContent='Signing in…'; try { await api('admin-login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))}); location.href='dashboard.html'; } catch(err){ $('#loginNotice').textContent=err.message; } });
}

let page=1,total=0,perPage=10;
async function load(){
  if (!$('#rows')) return;
  try { await api('admin-session'); } catch { location.href='index.html'; return; }
  const qs = new URLSearchParams({page,perPage,search:$('#search').value,status:$('#status').value,from:$('#from').value,to:$('#to').value,sort:$('#sort').value});
  const res = await api(`applications?${qs}`, {headers:{}}); total=res.count||0; renderCards(res.stats); renderRows(res.data||[]); $('#pageInfo').textContent=`Page ${page} of ${Math.max(1,Math.ceil(total/perPage))}`;
}
function renderCards(s){ $('#cards').innerHTML = [['Total',s.total],['Pending',s.pending],['Approved',s.approved],['Rejected',s.rejected],['Today',s.today],['This Month',s.month]].map(([k,v])=>`<div class="card"><b>${v}</b><span>${k}</span></div>`).join(''); }
function badge(st){ return `<span class="badge ${String(st).replace(/\s/g,'')}">${st}</span>`; }
function renderRows(rows){ $('#rows').innerHTML = rows.length ? rows.map(r=>`<tr><td>${r.reference_code||r.id}</td><td>${r.full_name||''}</td><td>${r.phone||''}</td><td>${r.email||''}</td><td>${badge(r.status)}</td><td>${new Date(r.created_at).toLocaleString()}</td><td class="actions"><button onclick="viewApp('${r.id}')">View</button><button onclick="editApp('${r.id}')">Edit</button><button class="danger" onclick="delApp('${r.id}')">Delete</button></td></tr>`).join('') : '<tr><td colspan="7">No applications found.</td></tr>'; }
async function viewApp(id, edit=false){ const {data}=await api(`application-details?id=${encodeURIComponent(id)}`,{headers:{}}); const files=await Promise.all((data.files||[]).map(async f=>{ try{ const u=await api(`application-file?path=${encodeURIComponent(f.path)}`,{headers:{}}); return {...f,url:u.signedUrl}; }catch{return f;} })); const hidden=['files']; $('#modalBody').innerHTML=`<h2>${edit?'Edit':'Application'}: ${data.full_name||data.reference_code}</h2><p>${badge(data.status)} · Submitted ${new Date(data.created_at).toLocaleString()}</p><label>Status<select id="detailStatus">${statuses.map(s=>`<option ${s===data.status?'selected':''}>${s}</option>`).join('')}</select></label><div class="detail-grid">${Object.entries(data).filter(([k])=>!hidden.includes(k)).map(([k,v])=>`<div class="detail"><span>${k.replaceAll('_',' ')}</span>${edit && !['id','created_at','updated_at','reference_code','status'].includes(k)?`<textarea class="edit" data-key="${k}">${Array.isArray(v)?v.join(', '):(v??'')}</textarea>`:`<strong>${Array.isArray(v)?v.join(', '):(v??'')}</strong>`}</div>`).join('')}</div><h3>Uploaded files</h3>${files.length?files.map(f=>`<p><strong>${f.field}</strong><br>${f.mimeType?.startsWith('image/')?`<a href="${f.url}" target="_blank"><img class="file-preview" src="${f.url}" alt="${f.field}"></a>`:`<a href="${f.url}" target="_blank">Open file</a>`}</p>`).join(''):'<p>No files uploaded.</p>'}<p><button class="btn" onclick="saveStatus('${id}')">Save status</button>${edit?` <button class="btn" onclick="saveEdit('${id}')">Save edits</button>`:''}</p>`; $('#modal').classList.add('show'); }
async function editApp(id){ viewApp(id,true); }
async function saveStatus(id){ await api('update-status',{method:'POST',body:JSON.stringify({id,status:$('#detailStatus').value})}); await load(); alert('Status updated.'); }
const camel={sender_name:'senderName',txn_id:'txnId',full_name:'fullName',gender_other:'genderOther',applicant_status:'status',applicant_status_other:'statusOther',association_other:'associationOther',heard_from:'heardFrom',heard_from_other:'heardFromOther',why_join:'whyJoin',want_learn:'wantLearn',main_goal:'mainGoal',interest_areas:'interestAreas',interest_areas_other:'interestAreasOther',willing_active:'willingActive',time_available:'timeAvailable',willing_tasks:'willingTasks',join_volunteer:'joinVolunteer',preferred_area:'preferredArea',why_volunteer:'whyVolunteer',willing_contribute:'willingContribute',anything_else:'anythingElse'};
async function saveEdit(id){ const body={id}; document.querySelectorAll('.edit').forEach(t=>{ body[camel[t.dataset.key]||t.dataset.key]=t.value; }); await api('update-application',{method:'POST',body:JSON.stringify(body)}); await load(); alert('Application updated.'); }
async function delApp(id){ if(!confirm('Delete this application and associated files?')) return; await api('delete-application',{method:'POST',body:JSON.stringify({id})}); await load(); }
window.viewApp=viewApp; window.editApp=editApp; window.saveStatus=saveStatus; window.saveEdit=saveEdit; window.delApp=delApp;
if ($('#rows')) { $('#applyFilters').onclick=()=>{page=1;load()}; $('#prev').onclick=()=>{if(page>1){page--;load()}}; $('#next').onclick=()=>{if(page<Math.ceil(total/perPage)){page++;load()}}; $('#closeModal').onclick=()=>$('#modal').classList.remove('show'); $('#logoutBtn').onclick=async()=>{await api('admin-logout',{method:'POST'});location.href='index.html'}; load(); }
